//
//  MainInteractor.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func fetchFavorites(request: Main.Favorite.Request)
}

protocol MainDataStore
{
    //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchFavorites(request: Main.Favorite.Request)
    {
        worker = MainWorker()
        worker?.fetchFavorites()
        
        let response = Main.Favorite.Response()
        presenter?.presentFavorites(response: response)
    }
}
