//
//  MainPresenter.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentFavorites(response: Main.Favorite.Response)
    func presentFavoritesError(response: Main.Error.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentFavorites(response: Main.Favorite.Response)
    {
        var metas = [ChannelMeta]()
        
        let pref = Preferences.getPreferences()
        for fav in pref.favorites {
            metas += [fav]
        }
        
        print("favorites: \(pref.favorites)")
        
        let viewModel = Main.Favorite.ViewModel(metas: metas)
        self.viewController?.displayFavorites(viewModel: viewModel)
        
        /*DispatchQueue.global().async {
            
            /*for meta in response.metas {
                for fav in pref.favorites {
                    if meta.channelId == fav.channelId {
                        meta.isFavorite = true
                        metas += [meta]
                        break
                    }
                }
            }*/
            
            
            DispatchQueue.main.async {
                
            }
        }*/
    }
    
    func presentFavoritesError(response: Main.Error.Response) {
        let viewModel = Main.Error.ViewModel(message: response.message)
        viewController?.displayFavoritesError(viewModel: viewModel)
    }
}
