//
//  ChannelsPresenter.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelsPresentationLogic
{
    func presentChannels(response: Channels.List.Response)
}

class ChannelsPresenter: ChannelsPresentationLogic
{
    weak var viewController: ChannelsDisplayLogic?
    
    // MARK: Do something
    
    func presentChannels(response: Channels.List.Response)
    {
        let viewModel = Channels.List.ViewModel()
        viewController?.displayChannels(viewModel: viewModel)
    }
}
