//
//  ChannelsInteractor.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChannelsBusinessLogic
{
    func fetchChannels(request: Channels.List.Request)
}

protocol ChannelsDataStore
{
    //var name: String { get set }
}

class ChannelsInteractor: ChannelsBusinessLogic, ChannelsDataStore
{
    var presenter: ChannelsPresentationLogic?
    var worker: ChannelsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchChannels(request: Channels.List.Request)
    {
        worker = ChannelsWorker()
        worker?.fetchChannels()
        
        let response = Channels.List.Response()
        presenter?.presentChannels(response: response)
    }
}
