//
//  ChannelsModels.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Channels
{
    // MARK: Use cases
    
    enum List
    {
        struct Request
        {
        }
        
        struct Response
        {
            var channels = [Channel]()
        }
        
        struct ViewModel
        {
            var channels = [Channel]()
        }
    }
    
    enum Metadata {
        
        struct Response
        {
            var metas = [ChannelMeta]()
        }
        
        struct ViewModel
        {
            var metas = [ChannelMeta]()
        }
    }
    
    enum Favorite {
        struct Request {
            var meta = ChannelMeta()
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
    
    enum Error {
        
        struct Response {
            var message: String = ""
        }
        
        struct ViewModel {
            var message: String = ""
        }
    }
}
