//
//  ChannelsWorker.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChannelsWorker
{
    
    typealias ChannelFetchedHandler = () -> Void
    
    func fetchChannels()
    {
    }
}
