//
//  ChannelsModels.swift
//  Astro
//
//  Created by Suhendra Ahmad on 9/19/17.
//  Copyright (c) 2017 Ainasoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Channels
{
    // MARK: Use cases
    
    enum List
    {
        struct Request
        {
        }
        
        struct Response
        {
            var id: Int = 0
            var title: String = ""
            var stubNumber: Int = 0
        }
        
        struct ViewModel
        {
            var id: Int = 0
            var title: String = ""
            var stubNumber: Int = 0
        }
    }
}
